#title in header
title: '<span style="color: rgba(255, 211, 0, 1)">[<span style="color: rgba(255, 0, 0, 1)">zzerX</span>@<span style="color: rgba(0, 255, 0, 0.8)">blog</span> <span>~</span> ]:</span>'

#main info
#owner
owner: ""
# email: zzerx@qq.com
info: "Everything that drowns me makes me wanna fly."
#description
desc: ""

#menu
menu:
  # Works: /Works
  创作: /Artwork
  开发: /apps
  关于: /About

#index/main page max show posts (in number)
max_post: 10

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: minima
placelink: https://github.com/adisaktijrs/hexo-theme-minima
github: https://github.com/0x7A7A6572
bilibili: https://space.bilibili.com/3740018
tencent: http://wpa.qq.com/msgrd?v=3&uin=2623385294&site=qq&menu=yes
pixiv: https://www.pixiv.net/users/11023636
# linkedin: https://linkedin.com/in/adisaktijrs
# twitter: https://twitter.com/adisaktijrs
# instagram: https://instagram.com/adisaktijrs
# stackoverflow: https://stackoverflow.com/story/tobiasreithmeier
beian_info: 桂公网安备 45010502000772号
my_frok: https://github.com/0x7A7A6572/hexo-theme-minima

#左边侧栏
sidebar: 
  enable: true
  theme_switch: true
  to_top: true
  emil: true
  conversation_link: http://wpa.qq.com/msgrd?v=3&uin=2623385294&site=qq&menu=yes
  community: 
    github: https://github.com/0x7A7A6572
    # bilibili: https://space.bilibili.com/3740018
    pixiv: https://www.pixiv.net/users/11023636
    

# Misc
nanobar: /js/nanobar.min.js
switch_light: "1/0"
switch_dark: "0/1"

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true


# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io

#content-inner
content_inner:
   enable: true
   avatar: /images/favicon.png
   name: zzerX
   motto: "✨Everything that drowns me makes me wanna fly."



#tag显示配置
post_tag:
   enable: true
   aside_tag_enable: true
   style: "simble" # defult or simble(only display color)
   bind_color:
     lua: b900dc
     java: dc0f00
     js: 0FA0CE
     linux: dc550f
     h5: 00bedc
     termux: 2b2b2b
     html: FF33EB
     android: FFE600
     git: 6600FF
     element: 008fdd
     vue: 0fdc00

#github热力图
github_heatmap:
  enable: false
  user: "0x7A7A6572"
  hexcolor: 03adfc

#文章日历热力图
postCalendar: 
  enable: false
  title: "文章日历"
  titleColor: 3C4858
  range: 5
  visualMapColor: ["'#d5d5d5'", "'#c6e48b'", "'#7bc96f'","'#239a3b'","'#196127'"]
  visualMapCategories: [0, 1, 2, 3, 4]


libs:
  js:
    echarts: https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/echarts.min.js
    jquery: 


#留言板系统
messageBoard:
  enable: true
  owner: "0x7A7A6572"
  repo: MessageBoard
  oauth:
    client_id: d6a47979b8d54944ecac
    client_secret: 2ae9b7a5ebb3ff9fa1a061c6925baff3397a26c4