#title in header
title: '<span style="color: rgba(255, 211, 0, 1)">[<span style="color: rgba(255, 0, 0, 1)">zzerX</span>@<span style="color: rgba(0, 255, 0, 0.8)">cnblogs</span> <span>~</span> ]:</span>'

#main info
#owner
owner: "欢迎来到我的博客！"
# email: zzerx@qq.com
info: "Everything that drowns me makes me wanna fly."
#description
desc: ""

#menu
menu:
  # Works: /Works
  创作: /Artwork
  开发: /DevApp
  关于: /About

#index/main page max show posts (in number)
max_post: 10

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: minima
placelink: https://github.com/adisaktijrs/hexo-theme-minima
github: https://github.com/0x7A7A6572
bilibili: https://space.bilibili.com/3740018
tencent: http://wpa.qq.com/msgrd?v=3&uin=2623385294&site=qq&menu=yes
pixiv: https://www.pixiv.net/users/11023636
# linkedin: https://linkedin.com/in/adisaktijrs
# twitter: https://twitter.com/adisaktijrs
# instagram: https://instagram.com/adisaktijrs
# stackoverflow: https://stackoverflow.com/story/tobiasreithmeier
beian_info: 桂公网安备 45010502000772号

#左边侧栏
sidebar: 
  enable: true
  theme_switch: true
  to_top: true
  emil: true
  conversation_link: http://wpa.qq.com/msgrd?v=3&uin=2623385294&site=qq&menu=yes
  community: 
    github: https://github.com/0x7A7A6572
    bilibili: https://space.bilibili.com/3740018
    pixiv: https://www.pixiv.net/users/11023636
    

# Misc
nanobar: /js/nanobar.min.js
switch_light: "1/0"
switch_dark: "0/1"

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true


# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io

#content-inner
content_inner:
   enable: true
   avatar: /images/favicon.png
   name: zzerX
   motto: "✨Everything that drowns me makes me wanna fly."

#github热力图
github_heatmap:
  enable: false
  user: "0x7A7A6572"
  hexcolor: 03adfc

#tag显示配置
post_tag:
   enable: true
   style: "defult" # defult or simble(only display color)
   bind_color:
     tagname1: 0fdc00
     lua: b900dc
     java: dc0f00
     js: 0FA0CE
     linux: dc550f
     h5: 00bedc
     termux: 2b2b2b


